[project]
name = "primalscheme3"
version = "3.3.0"
description = "Generation of highly multiplexed primer schemes"
authors = [{ name = "ChrisKent", email = "chrisgkent@gmail.com" }]
requires-python = "~=3.11"
readme = "README.md"
license = "GPL-3.0-only"
dependencies = [
    "primer3-py>=2.2.0,<3",
    "networkx~=3.1",
    "kaleido==0.2.1",
    "plotly>=5.16.1,<6",
    "tqdm>=4.66.1,<5",
    "typer>=0.16.1,<0.17",
    "primalbedtools>=0.10.1,<0.11",
    "dnaio>=1.2.3,<2",
    "matplotlib>=3.10.5,<4",
    "primalschemers>=0.1.9,<0.2",
    "numpy>=2.3.0",
]

[project.urls]
Repository = "https://github.com/artic-network/primalscheme3"

[project.scripts]
primalscheme3 = "primalscheme3.cli:app"

[dependency-groups]
dev = [
    "pytest-cov>=4.1.0,<5",
    "ruff>=0.11.4,<0.12",
    "pytest>=7.4.2,<8",
    "pre-commit>=4.0.1,<5",
    "pytest-xdist>=3.6.1,<4",
    "coverage>=7.8.0,<8",
]
docs = [
    "mkdocs-material>=9.5.27,<10",
    "mkdocs>=1.6.1,<2",
]

[tool.uv]
default-groups = [
    "dev",
    "docs",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # isort
    "I",
]
ignore = ["E501"]
