config_dict = {
    "n_cores": 1,
    "amplicon_size_min": 360,
    "amplicon_size_max": 400,
    "min_overlap": 10,
    "mv_conc": 100.0,
    "dv_conc": 2.0,
    "dntp_conc": 0.8,
    "dna_conc": 15.0,
    "primer_gc_min": 30,
    "primer_gc_max": 55,
    "primer_tm_min": 59.5,
    "primer_tm_max": 62.5,
    "primer_homopolymer_max": 5,
    "primer_hairpin_th_max": 47.0,
    "editdist_max": 1,
    "editdist_end3p": 6,
    "primer_size_max": 36,
    "primer_size_min": 18,
    "primer_max_walk": 80,
    "minbasefreq": 0,
    "reducekmers": False,
    "dimerscore": -27,
}


AMBIGUOUS_DNA = {
    "M": "AC",
    "R": "AG",
    "W": "AT",
    "S": "CG",
    "Y": "CT",
    "K": "GT",
    "V": "ACG",
    "H": "ACT",
    "D": "AGT",
    "B": "CGT",
}
ALL_DNA = {
    "A": "A",
    "C": "C",
    "G": "G",
    "T": "T",
    "M": "AC",
    "R": "AG",
    "W": "AT",
    "S": "CG",
    "Y": "CT",
    "K": "GT",
    "V": "ACG",
    "H": "ACT",
    "D": "AGT",
    "B": "CGT",
}
ALL_BASES = {
    "A",
    "C",
    "G",
    "T",
    "M",
    "R",
    "W",
    "S",
    "Y",
    "K",
    "V",
    "H",
    "D",
    "B",
}
AMB_BASES = {"Y", "W", "R", "B", "H", "V", "D", "K", "M", "S"}
AMBIGUOUS_DNA_COMPLEMENT = {
    "A": "T",
    "C": "G",
    "G": "C",
    "T": "A",
    "M": "K",
    "R": "Y",
    "W": "W",
    "S": "S",
    "Y": "R",
    "K": "M",
    "V": "B",
    "H": "D",
    "D": "H",
    "B": "V",
    "X": "X",
    "N": "N",
}
