name: CI
on:
  push:
    paths:
      - "primalscheme3/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/pytest.yml"

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
        poetry-version: ["2.1.3"]
        os: [ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install and test via pip
      - name: install via pip
        run: pip install .
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest .
